/*

 EXPORT.C

 Tile Source File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

const unsigned char TileLabelTLE0[] =
{
  0x81,0xFF,0x7E,0x81,0x7E,0x81,0x7E,0x81,
  0x7E,0x81,0x7E,0x81,0x7E,0x81,0x81,0xFF
};

/* End of EXPORT.C */
