/*

 EXPORT.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Export_h_INCLUDE
#define __Export_h_INCLUDE

/* Bank of tiles. */
#define TileLabelBank 0
extern const unsigned char TileLabelTLE0[];

#endif

/* End of EXPORT.H */
